# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='student',
            new_name='students',
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
