# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170528_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='api.Type'),
            preserve_default=False,
        ),
    ]
