version: '2'
services:
  db:
    container_name: db-tcc
    image: postgres
    ports:
      - "5432:5432"
  web:
    container_name: api-tcc
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
